services:
  waycoffee-web:
    build: .
    container_name: waycoffee-web
    ports:
      - "172.16.16.200:2223:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./sitemap.xml:/usr/share/nginx/html/sitemap.xml:ro
    restart: unless-stopped
    networks:
      - waycoffee-net

networks:
  waycoffee-net:
    driver: bridge
    name: waycoffee-net

